apiVersion: apps/v1
kind: Deployment
metadata:
  name: auntenticacion
  labels:
    app: auntenticacion
spec:
  replicas: 1
  template:
    metadata:
      name: auntenticacion
      labels:
        app: auntenticacion
    spec:
      containers:
        - name: auntenticacion
          image: mrsimonty/auntenticacion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: auntenticacion